name: generic-programming-munihac
version: '2018'
author: Andres Löh <andres@well-typed.com>
license: UnspecifiedLicense
dependencies:
- base
- sop-core >=0.4 && <0.5
- generics-sop >=0.4.0.1 && <0.5
library:
  source-dirs: src
  exposed-modules:
  - Demo
tests:
  translc:
    source-dirs:
    - src
    - test
    main: Spec.hs
    dependencies:
    - generic-programming-munihac
    - hspec
    - async
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
